x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  postgres:
    <<: *default-logging
    container_name: futureJudge-Postgres-Prod
    image: postgres:16-alpine
    ports:
      - "127.0.0.1:5100:5432"
    environment:
      POSTGRES_DB: futureJudge-prod
      POSTGRES_HOST_AUTH_METHOD: trust
      PGUSER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 2s
      retries: 5
  solidQueuePostgres:
    <<: *default-logging
    container_name: solidQueue-Postgres-Prod
    image: postgres:16-alpine
    ports:
      - "127.0.0.1:6100:5432"
    environment:
      POSTGRES_DB: futureJudge-prod
      POSTGRES_HOST_AUTH_METHOD: trust
      PGUSER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 2s
      retries: 5
  futureJudgeProd:
    <<: *default-logging
    privileged: true
    depends_on:
      postgres:
        condition: service_healthy
    container_name: futureJudgeProd
    image: future-judge-prod
    build:
      context: .
      dockerfile: prod.Dockerfile
    env_file:
      - .env.production
    ports:
      - "127.0.0.1:3100:3000"