x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  postgresDev:
    <<: *default-logging
    container_name: futureJudge-Postgres-Dev
    image: postgres:17-alpine
    ports:
      - "127.0.0.1:2001:5432"
    environment:
      POSTGRES_DB: futureJudge-dev
      POSTGRES_HOST_AUTH_METHOD: trust
      PGUSER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 2s
      retries: 5
  solidQueuePostgresDev:
    <<: *default-logging
    container_name: solidQueue-Postgres-Dev
    image: postgres:17-alpine
    ports:
      - "127.0.0.1:2002:5432"
    environment:
      POSTGRES_DB: queue
      POSTGRES_HOST_AUTH_METHOD: trust
      PGUSER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 2s
      retries: 5
  solidCachePostgresDev:
    <<: *default-logging
    container_name: solidCache-Postgres-Dev
    image: postgres:17-alpine
    ports:
      - "127.0.0.1:2003:5432"
    environment:
      POSTGRES_DB: cache
      POSTGRES_HOST_AUTH_METHOD: trust
      PGUSER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 2s
      retries: 5
  solidCablePostgresDev:
    <<: *default-logging
    container_name: solidCable-Postgres-Dev
    image: postgres:17-alpine
    ports:
      - "127.0.0.1:2004:5432"
    environment:
      POSTGRES_DB: cable
      POSTGRES_HOST_AUTH_METHOD: trust
      PGUSER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 2s
      retries: 5
  futureJudgeDev:
    <<: *default-logging
    privileged: true
    #    Uncomment the line below when using cgroup v2 and isolate v2
    #    cgroup: host
    depends_on:
      postgresDev:
        condition: service_healthy
    container_name: futureJudgeDev
    image: future-judge-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env.development
    volumes:
      - ./Gemfile.lock:/futureJudge/Gemfile.lock
      - ./app:/futureJudge/app
      - ./bin:/futureJudge/bin
      - ./config:/futureJudge/config
      - ./db:/futureJudge/db
      - ./lib:/futureJudge/lib
      - ./public:/futureJudge/public
      - ./spec:/futureJudge/spec
      - ./storage:/futureJudge/storage
      - ./vendor:/futureJudge/vendor
      - ./.ruby-version:/futureJudge/.ruby-version
      - ./config.ru:/futureJudge/config.ru
      - ./LICENSE:/futureJudge/LICENSE
      - ./test:/futureJudge/test
    ports:
      - "127.0.0.1:2000:3000"

  # ================= svix =================

  svix-dbDev:
    container_name: svix-db-dev
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PASSWORD-PLACEHOLDER--KsoIMcchtp
      POSTGRES_DB: svix
    volumes:
      - svix-postgres-dev-data:/var/lib/postgresql/data

  svix-redisDev:
    container_name: svix-redis-dev
    image: docker.io/redis:7-alpine
    command: --save 60 500 --appendonly yes --appendfsync everysec --requirepass PASSWORD-PLACEHOLDER--oVn8GSD6b9
    volumes:
      - svix-redis-dev-data:/data

  svix-serverDev:
    container_name: svix-server-dev
    image: svix/svix-server
    environment:
      WAIT_FOR: 'true'
      SVIX_REDIS_DSN: redis://:PASSWORD-PLACEHOLDER--oVn8GSD6b9@svix-redis-dev:6379
      SVIX_DB_DSN: postgres://postgres:PASSWORD-PLACEHOLDER--KsoIMcchtp@svix-db-dev:5432/svix
      SVIX_CACHE_TYPE: memory
      SVIX_JWT_SECRET: secret
      SVIX_LOG_LEVEL: trace
      SVIX_QUEUE_TYPE: redis
      SVIX_WHITELIST_SUBNETS: "[127.0.0.1/32, 172.17.0.0/16]"
    ports:
      - 2005:8071
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
    - svix-redisDev
    - svix-dbDev


volumes:
  svix-redis-dev-data:
  svix-postgres-dev-data:
